package com.nutri_sci.model;

import java.util.Map;

/**
 * Represents a food swap suggestion generated by the SwapEngine.
 * <p>
 * A SwapSuggestion contains all the information needed to present a food
 * swap recommendation to the user, including the suggested food item,
 * its nutritional impact, and a scoring assessment. The class provides
 * detailed breakdowns of how the swap would affect the user's nutritional
 * intake both in absolute terms and as percentages.
 * </p>
 * <p>
 * This data-holding class is immutable to ensure consistency during
 * the swap evaluation and presentation process.
 * </p>
 * 
 * @author Juliett
 * @version 1.0
 * @since 1.0
 * @see com.nutri_sci.service.SwapEngine
 */
public class SwapSuggestion {

    /** The name of the suggested food item */
    private final String foodName;
    
    /** The food group category of the suggested item */
    private final String foodGroup;
    
    /** The calculated score indicating how well this swap meets the user's goals */
    private final double finalScore;
    
    /** Absolute nutritional changes (key: nutrient name, value: change in grams or kcal) */
    private final Map<String, Double> nutrientChanges;
    
    /** Relative nutritional changes (key: nutrient name, value: percentage change as decimal) */
    private final Map<String, Double> nutrientPercentChanges;

    /**
     * Constructs a new swap suggestion with complete nutritional analysis.
     * 
     * @param foodName the name of the suggested food item
     * @param foodGroup the food group category (e.g., "Meat and Alternatives", "Vegetables")
     * @param finalScore the calculated score indicating swap quality (higher is better)
     * @param nutrientChanges absolute changes in nutrients (e.g., "Protein" -> +5.2)
     * @param nutrientPercentChanges relative changes as decimals (e.g., "Protein" -> 0.15 for +15%)
     */
    public SwapSuggestion(String foodName, String foodGroup, double finalScore, Map<String, Double> nutrientChanges, Map<String, Double> nutrientPercentChanges) {
        this.foodName = foodName;
        this.foodGroup = foodGroup;
        this.finalScore = finalScore;
        this.nutrientChanges = nutrientChanges;
        this.nutrientPercentChanges = nutrientPercentChanges;
    }

    /**
     * Gets the name of the suggested food item.
     * 
     * @return the food name
     */
    public String getFoodName() { return foodName; }
    
    /**
     * Gets the food group category of the suggested item.
     * 
     * @return the food group (e.g., "Meat and Alternatives", "Vegetables")
     */
    public String getFoodGroup() { return foodGroup; }
    
    /**
     * Gets the calculated score for this swap suggestion.
     * 
     * @return the final score (higher values indicate better matches to user goals)
     */
    public double getFinalScore() { return finalScore; }
    
    /**
     * Gets the absolute nutritional changes that would result from this swap.
     * 
     * @return a map of nutrient names to absolute changes in grams or kcal
     */
    public Map<String, Double> getNutrientChanges() { return nutrientChanges; }
    
    /**
     * Gets the relative nutritional changes that would result from this swap.
     * 
     * @return a map of nutrient names to percentage changes as decimals (0.15 = +15%)
     */
    public Map<String, Double> getNutrientPercentChanges() { return nutrientPercentChanges; }

    /**
     * Returns an HTML-formatted string representation for UI display.
     * <p>
     * This method formats the swap suggestion for display in user interface
     * components, showing the food name prominently and key nutritional
     * changes (calories, protein, fiber) with both absolute and percentage
     * values in a compact format.
     * </p>
     * 
     * @return HTML-formatted string suitable for display in JLabels or JLists
     */
    @Override
    public String toString() {
        return String.format("<html><b>%s</b><br>" +
                        "<font size='-2'>Calories: %+.2f kcal (%+.1f%%) | Protein: %+.2fg (%+.1f%%) | Fiber: %+.2fg (%+.1f%%)</font></html>",
                foodName,
                nutrientChanges.getOrDefault("Calories", 0.0),
                nutrientPercentChanges.getOrDefault("Calories", 0.0) * 100,
                nutrientChanges.getOrDefault("Protein", 0.0),
                nutrientPercentChanges.getOrDefault("Protein", 0.0) * 100,
                nutrientChanges.getOrDefault("Fiber", 0.0),
                nutrientPercentChanges.getOrDefault("Fiber", 0.0) * 100
        );
    }
}